-- =============================================================
-- DATA ANGGOTA KSU CAHAYA DHAMMA PHALA
-- Sumber: Dokumen/DAFTAR ANGGOTA KSU CAHAYA DHAMMA PHALA.xlsx
-- 171 anggota (163 aktif + 8 non-aktif)
-- Non-aktif: Keluar (Winarti #6) + Meninggal Dunia (7 orang)
-- Member #73 tidak ada di file sumber
-- join_date default: 2016-02-01 (tanggal badan hukum)
-- =============================================================

insert into public.members (member_number, name, address, phone, join_date, status, notes)
values
  (1, 'Aniah', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (2, 'Kuswono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (3, 'Sudirno', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (4, 'Sono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (5, 'Karsidi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (6, '(Winarti)', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'inactive', 'Keluar'),
  (7, 'Suroto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (8, 'Suwanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (9, 'Rusmini', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (10, 'Adi Wahyono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (11, 'Saimah', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (12, 'Tasman', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (13, 'Siyo Dwiroso', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (14, 'Resmini', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (15, 'Samyono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (16, 'Santosa', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (17, 'Suyono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (18, 'Maryono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (19, 'Karyono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (20, 'Waluyo', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (21, 'Budiono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (22, 'Darmanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (23, 'Saroji', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (24, '(Paryati)', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'inactive', 'Meninggal Dunia'),
  (25, 'Darmaji', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (26, 'Tarko', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (27, 'Tumijah', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'inactive', 'Meninggal Dunia'),
  (28, 'Padmo Susilo', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (29, 'Miskiyah', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (30, 'Karjono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (31, 'Sabar Wiyono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (32, 'Mursono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (33, 'Karsih', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (34, 'Sarijem', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (35, 'Rahmadi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (36, 'Manisi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (37, 'Litik', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (38, 'Darmono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (39, 'Sumini', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (40, 'Handi Cahyono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (41, 'Sati', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (42, 'Tarmono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (43, 'Minardi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (44, 'Ratmi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (45, 'Oru Wasaton', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (46, 'Sri Hartati', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (47, 'Waridi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (48, 'Juliyah', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (49, 'Vijja Ratano', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (50, 'Purwadi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (51, 'Dwi Vijjayanti', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (52, 'Tato', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (53, 'Panjiono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (54, 'Parsih', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (55, 'Suryadi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (56, 'Aris Bodi Ratana', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (57, 'Darwito', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (58, 'Taryuti/Siti', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (59, 'Saji', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (60, 'Waginah', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (61, 'Kami', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (62, 'Sartin', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (63, 'Jumini', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (64, 'Darmo Wiryo', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (65, 'Rusmiyati', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (66, 'Priyono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (67, 'Sariem', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (68, 'Suharjanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (69, 'Kasmi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (70, 'Parso', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (71, 'Catur Setyani', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (72, 'Slamet Sutir', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (74, 'Purwati', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (75, 'Wanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (76, 'Sudarma Widya', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (77, 'Cipret Darmanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (78, 'Ginem', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (79, 'Painten', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (80, 'Dwiyanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (81, 'Marno', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (82, 'Timba Suyono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (83, 'Karnoto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (84, 'Yogi Dwiyanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (85, 'Nanang Heri Susanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (86, 'Kanti Paraswati', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (87, 'Kuat Siti Kirana', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (88, 'Temi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (89, 'Ranem', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (90, 'Kiwil', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (91, 'Legowo Turah Suwanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (92, 'Slamet Suwanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (93, 'Mudita', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (94, 'Urip Widodo', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (95, 'Ragil Krisnandani', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (96, 'Diana Paramita', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (97, 'Marsih', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (98, 'Metta Candra Dewi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (99, 'Kartina', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (100, 'Rusmini Cemles', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (101, 'Wahyuni Saji', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (102, 'Suwarti', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (103, 'Rumini', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'inactive', 'Meninggal Dunia'),
  (104, 'Santi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (105, 'Nisem', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (106, 'Via Septiana', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (107, 'Mislam', 'Dusun Pringamba, Desa Aribaya, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (108, 'Warniem', 'Dusun Pringamba, Desa Aribaya, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (109, 'Kamto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (110, 'Suminah', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (111, 'Veni Eka Arativi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (112, 'Mega Setiana', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (113, 'Kadi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (114, 'Arif Setiyadi', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (115, 'Meri Kristanti', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (116, 'Turah Karjono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (117, 'Marsinem', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (118, 'Waluyo Ragil', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (119, 'Lewih', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (120, 'Karni', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (121, 'Utami', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (122, 'Oki Widya Dharma', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (123, 'Laxmi  Widyaningsih', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (124, 'Triwidata', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (125, 'Tarsini', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (126, 'Juliyanto', 'Dusun Pringamba, Desa Aribaya,  Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (127, 'Diyanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (128, 'Diyanti', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (129, 'Haryono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (130, 'Sabdono', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (131, 'Sartiyah', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (132, '(Karsinah)', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'inactive', 'Meninggal Dunia'),
  (133, 'Lebuh', 'Desa Pagentan, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (134, '(Ristono)', 'Dusun Windusaei, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'inactive', 'Meninggal Dunia'),
  (135, '(Tumini)', 'Dusun Windusaei, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'inactive', 'Meninggal Dunia'),
  (136, 'Hartati', 'Desa Pagentan, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (137, 'Suratno', 'Desa Pagentan, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (138, 'Lamini', 'Dusun Pringamba, Desa Aribaya, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (139, 'Metta Selina', 'Dusun Pringamba, Desa Aribaya, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (140, 'Ny. Akhmadi', 'Dusun Pringamba, Desa Aribaya, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (141, 'Manis', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (142, 'Budi Rahayu', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (143, 'Yanti    (Sono)', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (144, 'Leni', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (145, 'Ika Kurniasih', 'Dusun Tanjung, Desa Metawana, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (146, '(Parmono/Maniem)', 'Dusun Pringamba, Desa Aribaya, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'inactive', 'Meninggal Dunia'),
  (147, 'Wartini', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (148, 'Wahyu Darmawan', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (149, 'Suwito', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (150, 'Vitta Anggira', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (151, 'Turyanto (Madiono)', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (152, 'Gini', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (153, 'Selfi Dhammayanti', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (154, 'Darmanto Darman', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (155, 'Dedi Aditya', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (156, 'Pardikin', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (157, 'Komala Khemavanti', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (158, 'Wartam', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (159, 'Sabar Suyanto', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (160, 'Tukimin', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (161, 'Saliyah', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (162, 'Marsito', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (163, 'Hartini', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (164, 'Sunarti', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (165, 'Marti Farida', 'Desa Pagentan, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (166, 'Saryanti', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (167, 'Sunarjo', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (168, 'Retno Aji Utomo', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (169, 'Rosi Widyarti', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (170, 'Karnen', 'Dusun Windusari, Desa Sokaraja, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (171, 'Eko Kurniadi', 'Desa Metaana, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL),
  (172, 'Sri Purwaningsih', 'Desa Metaana, Kec. Pagentan, Kab. Banjarnegara', NULL, '2016-02-01', 'active', NULL)

on conflict (member_number) do nothing;
